name: Update notebooks

on:
  workflow_dispatch:

jobs:
  update:
    name: Update notebooks
    runs-on: 'ubuntu-24.04'

    steps:
      - uses: actions/checkout@v4
        with:
          path: notebooks
      - uses: actions/checkout@v4
        with:
          repository: ess-dmsc-dram/winter-school
          path: source

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: |
          cd source
          python strip_solutions.py ../notebooks
          cd ..

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          path: notebooks
          commit-message: 'Update notebooks'
          title: 'Update notebooks'
          body: 'This PR updates the notebooks.'
          branch: update-notebooks
